name: Maven CI/CD
on: push
jobs: 
  build_and_test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Set up JDK 8"
        uses: actions/setup-java@v1
        with: 
          java-version: 8
      - 
        uses: actions/cache@v2
        with: 
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          path: ~/.m2/repository
          restore-keys: "${{ runner.os }}-maven-\n"
      - 
        name: "Build project with Maven"
        run: "mvn -B package --file pom.xml"
      - 
        name: "Upload Maven build artifact"
        uses: actions/upload-artifact@v2
        with: 
          name: artifact.jar
          path: /Sparksamples/target/sparkTest2021-1.0-SNAPSHOT.jar
